### ISSUE TITLE
Posso ter uma cópia em execução no android studio

### ISSUE THREAD

**Issue by voobl** [SlipkHunter/SocksHttp#4]
Obrigado por este excelente trabalho

Posso ter uma cópia em execução no android studio

**Comment by marlonbr987** [comment]
mtv96385@gmail.com

Em 12 de mai de 2020 8:40 PM, "voobl" <notifications@github.com> escreveu:

**Comment by SlipkHunter** [comment]
> Obrigado por este excelente trabalho
> 
> Posso ter uma cópia em execução no android studio

Sim. Mas é possível que tenha que adaptar o Gradle para o correto funcionamento. '-'

**Comment by marlonbr987** [comment]
Me ajuda com o Project seu slipk hunter ele fica dando error toda hora eu já baixei todas as livrarias
