### ISSUE TITLE
pdnsd servidor sem tun2socks

### ISSUE THREAD

**Issue by EduSSH** [SlipkHunter/SocksHttp#8]
Olá Boa tarde, eu sou desenvolvedor do TLS Tunnel, e estou trabalhando na integração do SSH, estou tendo problemas com resolução de DNS, quando o servidor não possue o udpgw só é possível navegar sem tunelar o DNS.
Eu ví no SocksHttp pelo log que você utiliza dns cache com o pdnsd.

E eu queria uma ajuda sua para solucionar isso.

**Comment by SlipkHunter** [comment]
Já resolvido?!
